# 消消乐

5*5矩阵，相邻（上下左右）且相同的数字超过三个，可以消掉，同时由于重力作用，上面没有消掉的数字会降落，继续这个过程

求最后矩阵中剩下的数字个数的最小值

In [2]:
#消消乐
 
def gravity(grid,visited):
    # print('before:',grid)
    for col in range(5):
        cnt=0
        for row in range(4,-1,-1):
            if grid[row][col]=='x':
                cnt+=1
            elif cnt>0:
                grid[row+cnt][col]=grid[row][col]
                grid[row][col]='x'
                visited[row][col],visited[row+cnt][col]=visited[row+cnt][col],visited[row][col]
    return grid
 
def judge(grid,i,j):
    if i<3 and grid[i+1][j]==grid[i][j] and grid[i+2][j]==grid[i][j]:
        return True
    if j<3 and grid[i][j+1]==grid[i][j] and grid[i][j+2]==grid[i][j]:
        return True
    if i<4 and j<4 and grid[i+1][j]==grid[i][j] and grid[i][j+1]==grid[i][j]:
        return True
    if i<4 and j<4 and grid[i+1][j]==grid[i][j] and grid[i+1][j+1]==grid[i][j]:
        return True
    if i>=1 and j>0 and grid[i][j-1]==grid[i][j] and grid[i-1][j]==grid[i][j]:
        return True
    return False
 
while 1:
    try:
        grid=[]
        for row in range(5):
            line=list(map(int,input().split()))
            grid.append(line)
        visited=[[0 for _ in range(5)] for _ in range(5)]
        direction=[[0,1],[1,0],[-1,0],[0,-1]]
        for k in range(5):
            for g in range(5):
                que = [[k, g]]
                num = grid[k][g]
                if num=='x' or visited[k][g] or not judge(grid,k,g):
                    continue
                else:
                    flag=0
                    while que:
                        i,j=que.pop(0)
                        for x,y in direction:   #满足两个以上则可以消除
                            if i+x>=0 and j+y>=0 and i+x<5 and j+y<5 and not visited[i+x][j+y] and grid[i+x][j+y]==num:
                                visited[i+x][j+y]=1
                                grid[i+x][j+y]='x'
                                flag+=1
                                que.append([i+x,j+y])
                    if flag>0:
                        visited[k][g]=1
                        grid[k][g]='x'
                        grid=gravity(grid,visited)
        print(grid)
        cnt=25
        for i in range(5):
            cnt-=grid[i].count('x')
        print(cnt)
 
    except:
        break


## 走迷宫


S 代表起点； # 代表墙； . 代表可以走通。通过复制（上下左右），任意选择其中一个S作为起点，如果能够走无穷多步则输出“Yes",否则输出“No”

In [3]:
# “”“并不一定对”“”
import numpy as np
 
def connect(input_map):
    n = input_map.shape[0]
    m = input_map.shape[1]
    output_map = np.zeros((n, m), dtype=np.int)
    map_count = 0
    for i in range(n):
        map_count += 1
        line = input_map[i]
        j = 0
        while j < m:
            if j == 0:
                if line[j] == '.' or line[j] == 'S':
                    output_map[i][j] = map_count
            else:
                if line[j] == '.' or line[j] == 'S':
                    output_map[i][j] = map_count
                else:
                    map_count += 1
            j += 1
    # fuse
    for i in range(1, n):
        for j in range(m):
            if output_map[i][j] != 0 and output_map[i-1][j] != 0 and output_map[i-1][j] != output_map[i][j]:
                k = j
                while k >= 0 and output_map[i][k] != 0:
                    output_map[i][k] = output_map[i-1][j]
                    k -= 1
                k = j
                while k < m and output_map[i][k] != 0:
                    output_map[i][k] = output_map[i - 1][j]
                    k += 1
    # fuse
    for i in range(n-2, -1, -1):
        for j in range(m):
            if output_map[i][j] != 0 and output_map[i+1][j] != 0 and output_map[i+1][j] != output_map[i][j]:
                k = j
                while k >= 0 and output_map[i][k] != 0:
                    output_map[i][k] = output_map[i+1][j]
                    k -= 1
                k = j
                while k < m and output_map[i][k] != 0:
                    output_map[i][k] = output_map[i+1][j]
                    k += 1
    return output_map
 
 
# i_map = [['#', '#', '.', '.', '.', '.'],
#          ['#', '.', 'S', '#', '.', '.'],
#          ['.', '.', '#', '.', '#', '#'],
#          ['.', '#', '#', '.', '.', '.']]
 
i_map = [['#', '#', '#', '.', '.'],
         ['#', '.', '.', '.', '#'],
         ['#', '#', '#', 'S', '#'],
         ['#', '#', '.', '.', '#'],
         ['#', '#', '#', '.', '#']]
 
# i_map = [['#', '#', '#'],
#          ['#', 'S', '#'],
#          ['.', '.', '.']]
 
# i_map = [['.', '#'],
#          ['#', 'S']]
 
s_point = []
i_map = np.array(i_map)
for i in range(i_map.shape[0]):
    for j in range(i_map.shape[1]):
        if i_map[i][j] == 'S':
            s_point = [i, j]
output_map = np.concatenate((i_map, i_map, i_map), axis=0)
output_map = np.concatenate((output_map, output_map, output_map), axis=1)
 
o_map = connect(output_map)
 
temp = []
for i in range(o_map.shape[0]):
    for j in range(o_map.shape[1]):
        if i == 0 or i == o_map.shape[0] or j == 0 or j == o_map.shape[1]:
            temp.append(o_map[i][j])
 
print(o_map[s_point[0] + i_map.shape[0]][s_point[1] + i_map.shape[1]])
if o_map[s_point[0] + i_map.shape[0]][s_point[1] + i_map.shape[1]] in temp:
    print('yes')
else:
    print('no')
 
for i in range(output_map.shape[0]):
    print(output_map[i])
 
for i in range(o_map.shape[0]):
    print(o_map[i])
 
 
# 扩展后的迷宫图
# ['#' '#' '#' '.' '.' '#' '#' '#' '.' '.' '#' '#' '#' '.' '.']
# ['#' '.' '.' '.' '#' '#' '.' '.' '.' '#' '#' '.' '.' '.' '#']
# ['#' '#' '#' 'S' '#' '#' '#' '#' 'S' '#' '#' '#' '#' 'S' '#']
# ['#' '#' '.' '.' '#' '#' '#' '.' '.' '#' '#' '#' '.' '.' '#']
# ['#' '#' '#' '.' '#' '#' '#' '#' '.' '#' '#' '#' '#' '.' '#']
# ['#' '#' '#' '.' '.' '#' '#' '#' '.' '.' '#' '#' '#' '.' '.']
# ['#' '.' '.' '.' '#' '#' '.' '.' '.' '#' '#' '.' '.' '.' '#']
# ['#' '#' '#' 'S' '#' '#' '#' '#' 'S' '#' '#' '#' '#' 'S' '#']
# ['#' '#' '.' '.' '#' '#' '#' '.' '.' '#' '#' '#' '.' '.' '#']
# ['#' '#' '#' '.' '#' '#' '#' '#' '.' '#' '#' '#' '#' '.' '#']
# ['#' '#' '#' '.' '.' '#' '#' '#' '.' '.' '#' '#' '#' '.' '.']
# ['#' '.' '.' '.' '#' '#' '.' '.' '.' '#' '#' '.' '.' '.' '#']
# ['#' '#' '#' 'S' '#' '#' '#' '#' 'S' '#' '#' '#' '#' 'S' '#']
# ['#' '#' '.' '.' '#' '#' '#' '.' '.' '#' '#' '#' '.' '.' '#']
# ['#' '#' '#' '.' '#' '#' '#' '#' '.' '#' '#' '#' '#' '.' '#']
 
# 连通图
# [0 0 0 3 3 0 0 0 6 6 0 0 0 9 9]
# [0 3 3 3 0 0 6 6 6 0 0 9 9 9 0]
# [0 0 0 3 0 0 0 0 6 0 0 0 0 9 0]
# [0 0 3 3 0 0 0 6 6 0 0 0 9 9 0]
# [0 0 0 3 0 0 0 0 6 0 0 0 0 9 0]
# [0 0 0 3 3 0 0 0 6 6 0 0 0 9 9]
# [0 3 3 3 0 0 6 6 6 0 0 9 9 9 0]
# [0 0 0 3 0 0 0 0 6 0 0 0 0 9 0]
# [0 0 3 3 0 0 0 6 6 0 0 0 9 9 0]
# [0 0 0 3 0 0 0 0 6 0 0 0 0 9 0]
# [0 0 0 3 3 0 0 0 6 6 0 0 0 9 9]
# [0 3 3 3 0 0 6 6 6 0 0 9 9 9 0]
# [0 0 0 3 0 0 0 0 6 0 0 0 0 9 0]
# [0 0 3 3 0 0 0 6 6 0 0 0 9 9 0] 
# [0 0 0 3 0 0 0 0 6 0 0 0 0 9 0]


SyntaxError: invalid character in identifier (<ipython-input-3-5167e43052d6>, line 1)